/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_openframeworks_exampleICubeXAndroid_OfxMidiIn */

#ifndef _Included_cc_openframeworks_exampleICubeXAndroid_OfxMidiIn
#define _Included_cc_openframeworks_exampleICubeXAndroid_OfxMidiIn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_openframeworks_exampleICubeXAndroid_OfxMidiIn
 * Method:    recvMidiData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_cc_openframeworks_exampleICubeXAndroid_OfxMidiIn_recvMidiData
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
